micronaut:
  server:
    port: ${PORT:8080}
#    cors:
#      enabled: true
#      configurations:
#        web:
#          allowCredentials: true
#          allowedMethods:
#            - OPTIONS
#            - POST
#            - PUT
#            - GET
#            - DELETE
#          exposedHeaders:
#            - Access-Control-Allow-Origin
#            - Access-Control-Allow-Headers
#            - Access-Control-Request-Method
#            - Access-Control-Request-Headers
#            - Origin
#            - Cache-Control
#            - Content-Type
#            - Authorization
  application:
    name: crudPessoaMaven

#datasources:
#  default:
#    url: ${JDBC_URL}
#    username: ${JDBC_USER}
#    password: ${JDBC_PASSWORD}
#    driverClassName: org.postgresql.Driver
#    dialect: POSTGRES

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        format_sql: true
